name: Chat GPT
description: a ChatGPT Issue
title: "[AI]: "
labels: ["bug"]
projects: ["octo-org/1"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
          Thanks for taking the time to fill out this form
  - type: input
    id: contact
    attributes:
      label: COntact
      placeholder: ex. email@git.hub
