name: Discord
description: Test
body:
- type: textarea
  attributes:
    value: "Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord."
- type: textarea
  attributes:
    value: "This is working now!"
