name: Tracking issue
about: Use this template for tracking new features.
title: "[DATE]: [FEATURE NAME]"
labels: tracking issue, needs triage
assignees: octocat
body:
- type: markdown
  attributes:
    value: "Bugs are the worst!"
